# Generated by Django 3.1.5 on 2021-03-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoard', '0002_auto_20210303_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Novel', 'Novel'), ('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year'), ('5th year', '5th year'), ('Other', 'Other')], default='Other', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='sub',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry ', 'Chemistry '), ('C ', 'C '), ('Engineering', 'Engineering'), ('Other', 'Other')], default='Other', max_length=12),
        ),
    ]
