# Generated by Django 3.1.5 on 2021-01-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoard', '0002_auto_20210124_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
    ]
