# Generated by Django 3.1.5 on 2021-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoard', '0004_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
