# Generated by Django 3.1.5 on 2021-03-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoard', '0005_order_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gate', 'Gate'), ('Novel', 'Novel'), ('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year'), ('5th year', '5th year'), ('All', 'Other')], default='Gate', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry ', 'Chemistry '), ('C ', 'C '), ('Engineering', 'Engineering'), ('All', 'Other')], default='Math', max_length=12),
        ),
    ]
