# Generated by Django 3.1.5 on 2021-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoard', '0006_auto_20210305_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_done',
            field=models.BooleanField(default=False),
        ),
    ]
