# Generated by Django 3.1.5 on 2021-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoard', '0007_order_has_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_ft8ewu.jpg', upload_to='product'),
        ),
    ]
